project:
  type: website
  output-dir: ../docs-site

website:
  title: "RED-X Documentation"
  navbar:
    title: "RED-X Documentation"
    pinned: false
    right:
      - icon: github
        href: https://github.com/agrifooddatacanada/OAC_Historical_Research_Data_Explorer_App

  sidebar:
    style: docked
    contents: 
      - text: Home
        file: index.qmd
      - getting-started.qmd
      - user-guide.qmd
      - section: "System Design"
        contents:
          - file: architecture.qmd
          - text: "API Guide"
            file: api.qmd
          - section: "Developer"
            contents:
              - file: dev.qmd
              - section: "Database Schema"
                contents: 
                  - text: "research_data"
                    file: Research_data_OCA_schema.md
                  - text: "keywords_node"
                    file: Keyword_node_OCA_schema.md
                  - text: "keywords_edge"
                    file: Keyword_edge_OCA_schema.md
                  - text: "authors_node"
                    file: Authors_node_OCA_schema.md
                  - text: "authors_edge"
                    file: Authors_edge_OCA_schema.md 
                  - text: "processed_studies"
                    file: Processed_OCA_schema.md
                  - text: "update_info"
                    file: Update_info_OCA_schema.md
                  - text: "college_colors"
                    file: college_colors_OCA_schema.md
                  - text: "department_colors"
                    file: Department_colors_OCA_schema.md

format:
  html:
    link-external-newwindow: true
    include-after-body: 
      - zoom.js
    number-sections: false
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 5
    toc-title: "On this page"







